--- 
- 
  gather_facts: false
  hosts: localhost
  name: "Create an instance"
  tasks: 
    - 
      gcp_compute_disk: 
        auth_kind: "{{ gcp_cred_kind }}"
        name: disk-instance
        project: "{{ gcp_project }}"
        scopes: 
          - "https://www.googleapis.com/auth/compute"
        service_account_file: "{{ gcp_cred_file }}"
        size_gb: 50
        source_image: projects/windows-cloud/global/images/windows-server-2012-r2-dc-core-v20200512
        state: present
        zone: "{{ zone }}"
      name: "create a disk"
      register: disk
   - 
      gcp_compute_network: 
        auth_kind: "{{ gcp_cred_kind }}"
        name: network-instance
        project: "{{ gcp_project }}"
        scopes: 
          - "https://www.googleapis.com/auth/compute"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      name: "create a network"
      register: network
    - 
      gcp_compute_address: 
        auth_kind: "{{ gcp_cred_kind }}"
        name: address-instance
        project: "{{ gcp_project }}"
        region: "{{ region }}"
        scopes: 
          - "https://www.googleapis.com/auth/compute"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      name: "create a address"
      register: address
    - 
      gcp_compute_instance: 
        auth_kind: "{{ gcp_cred_kind }}"
        disks: 
          - 
            auto_delete: true
            boot: true
            source: "{{ disk }}"
        machine_type: n1-standard-1
        name: test-vm
        network_interfaces: 
          - 
            access_configs: 
              - 
                name: "External NAT"
                nat_ip: "{{ address }}"
                type: ONE_TO_ONE_NAT
            network: "{{ network }}"
        project: "{{ gcp_project }}"
        scopes: 
          - "https://www.googleapis.com/auth/compute"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
        zone: "{{ zone }}"
      name: "create a instance"
      register: instance
  vars: 
    gcp_cred_file: /home/my_account.json
    gcp_cred_kind: serviceaccount
    gcp_project: my-project
    region: us-central1
    zone: us-central1-a
 - 
  connection: winrm
  hosts: new_instances
  name: "Manage new instances"
  roles: 
    - base_configuration
    - production_server
  sudo: true
